baseURL       = "https://sembrarycrecer.org/"
title         = "Sembrar y Crecer | Fundación"
theme         = "roxo-hugo"
summarylength = 25
googleAnalytics = "G-MBC1T5ET3Z"

languageCode  = "es"
defaultContentLanguage = 'es'
[languages]
  [languages.es]
    languageCode = 'es-CO'
    languageName = 'Español'
    title = 'Sembrar Y Crecer'
    weight = 1
    [languages.es.params.banner]
      enable = true
      background_image = "/images/backgrounds/hero-background.jpg"

  [languages.en]
    languageCode = 'en-US'
    languageName = 'English'
    title = 'Sembrar Y Crecer'
    weight = 2
    [languages.en.params.banner]
      enable = true
      background_image = "/images/backgrounds/hero-background.jpg"
# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "menu_home"
    url     = ".."
    weight  = 1
  [[menu.nav]]
    name    = "menu_gallery"
    url     = "gallery"
    weight  = 2
  [[menu.nav]]
    name    = "menu_blog"
    url     = "blog"
    weight  = 3
  [[menu.nav]]
    name    = "menu_privacy"
    url     = "pvpolicy"
    weight  = 4
  [[menu.nav]]
    name    = "menu_donate"
    url     = "donate"
    weight  = 4
  [[menu.nav]]
    name    = "menu_transparency"
    url     = "transparency"
    weight  = 4
  [[menu.nav]]
    name    = "menu_contact"
    url     = "contact"
    weight  = 5

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  favicon = true
  # Meta data
  description = "Sembrar y Crecer "
  author = "Sergio Cuervo"
  fabform  = "https://fabform.io/f/sCvLzvx"
  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "Nombre"
    placeholder_last_name         = "Apellido"
    placeholder_email             = "Email"
    placeholder_about_the_project = "Acerca de tu Propuesta"
    placeholder_phone             = "Telefono"
    send_message                  = "Enviar"

    [[params.contactForm.projectType]]
      value = "gd"
      title  = "Graphics Design"
    [[params.contactForm.projectType]]
      value = "wd"
      title  = "Web Design"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.jpg"
    heading               = "Sembramos creatividad, cultivamos educación con Propósito."
    tagline               = "Nosotros"

  [params.texts]
    enable    = true
    title1     = "NUESTRA HISTORIA"
    subtitle1  = "Aunque llevamos más de 20 años impactando vidas en toda Colombia, en 2023 formalizamos nuestra operación como SEMBRAR Y CRECER ONG, en las instalaciones de la finca Villa María ubicada en la vereda San Andrés de Mesa, Cundinamarca, impactando a cientos de niños, adultos y adultos mayores de todo el país, a través de nuestra escuela EmpoderArte y nuestros planes de voluntariado."
    title2    = "NUESTRO PROPÓSITO"
    subtitle2 = "Nuestro gran propósito es seguir creando espacios sanos, competitivos y confiables para las personas impactadas, partiendo desde la ruta del arte y las nuevas tecnologías como forma inicial de potencializar, salvaguardar, sanar y empoderar a todos los niños, jóvenes y adultos de todo el país, para que eleven su estándar de habilidades y conocimientos."
    title3    = "NUESTRO EJE"
    subtitle3 = "Sembrar y Crecer ONG basa su eje de impacto en la educación y cambio sistémico de comunidades rurales a través del arte (Escuela EmpoderArte) y nuevas tecnologías, con el objeto de elevar los estándares culturales de los niños y de su entorno brindándoles la oportunidad de mejorar su calidad de vida."
    title4    = "NUESTRAS GRANDES METAS"
    subtitle4 = "Impactar a más de 200 mil personas, fortaleciendo sus habilidades para la vida en familia y a nivel profesional, fomentando un cambio sistémico en su entorno y transformando su calidad de vida y su capacidad de impacto positivo."

  [params.call_to_action]
    enable              = false
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET’S WORK TOGETHER"
    primary_button      = "Submit Query"
    primary_button_url  = "contact"
    secondary_button    = "Not Convinced"
    secondary_button_url = "portfolio"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Información de contacto"
      address = "Vereda San Andres, La Mesa, Cundinamarca"
      phone   = "310-556-6599"
      email   = "Sembrarycrecer1@gmail.com"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "Blog"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Redes Sociales"
        [[params.footer.social.link]]
          name = "Facebook"
          url  = "https://www.facebook.com/profile.php?id=100090311177963&mibextid=ZbWKwL"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "https://instagram.com/sembrarycrecer?igshid=MzRlODBiNWFlZA=="
